/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRecomendacoesRouteImport } from './routes/_authenticated/recomendacoes'
import { Route as AuthenticatedPosVendaRouteImport } from './routes/_authenticated/pos-venda'
import { Route as AuthenticatedPlanejamentoRouteImport } from './routes/_authenticated/planejamento'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHotRouteImport } from './routes/_authenticated/hot'
import { Route as AuthenticatedFunilRouteImport } from './routes/_authenticated/funil'
import { Route as AuthenticatedEmDelayRouteImport } from './routes/_authenticated/em-delay'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCicloRevisaoRouteImport } from './routes/_authenticated/ciclo-revisao'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedAtividadesRouteImport } from './routes/_authenticated/atividades'
import { Route as AuthenticatedApolicesRouteImport } from './routes/_authenticated/apolices'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecomendacoesRoute =
  AuthenticatedRecomendacoesRouteImport.update({
    id: '/recomendacoes',
    path: '/recomendacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosVendaRoute = AuthenticatedPosVendaRouteImport.update({
  id: '/pos-venda',
  path: '/pos-venda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanejamentoRoute =
  AuthenticatedPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotRoute = AuthenticatedHotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunilRoute = AuthenticatedFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmDelayRoute = AuthenticatedEmDelayRouteImport.update({
  id: '/em-delay',
  path: '/em-delay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCicloRevisaoRoute =
  AuthenticatedCicloRevisaoRouteImport.update({
    id: '/ciclo-revisao',
    path: '/ciclo-revisao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtividadesRoute = AuthenticatedAtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApolicesRoute = AuthenticatedApolicesRouteImport.update({
  id: '/apolices',
  path: '/apolices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/apolices': typeof AuthenticatedApolicesRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ciclo-revisao': typeof AuthenticatedCicloRevisaoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/em-delay': typeof AuthenticatedEmDelayRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/hot': typeof AuthenticatedHotRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/pos-venda': typeof AuthenticatedPosVendaRoute
  '/recomendacoes': typeof AuthenticatedRecomendacoesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/apolices': typeof AuthenticatedApolicesRoute
  '/atividades': typeof AuthenticatedAtividadesRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/ciclo-revisao': typeof AuthenticatedCicloRevisaoRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/em-delay': typeof AuthenticatedEmDelayRoute
  '/funil': typeof AuthenticatedFunilRoute
  '/hot': typeof AuthenticatedHotRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/pos-venda': typeof AuthenticatedPosVendaRoute
  '/recomendacoes': typeof AuthenticatedRecomendacoesRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/apolices': typeof AuthenticatedApolicesRoute
  '/_authenticated/atividades': typeof AuthenticatedAtividadesRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/ciclo-revisao': typeof AuthenticatedCicloRevisaoRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/em-delay': typeof AuthenticatedEmDelayRoute
  '/_authenticated/funil': typeof AuthenticatedFunilRoute
  '/_authenticated/hot': typeof AuthenticatedHotRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planejamento': typeof AuthenticatedPlanejamentoRoute
  '/_authenticated/pos-venda': typeof AuthenticatedPosVendaRoute
  '/_authenticated/recomendacoes': typeof AuthenticatedRecomendacoesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/administracao'
    | '/apolices'
    | '/atividades'
    | '/calendario'
    | '/ciclo-revisao'
    | '/clientes'
    | '/dashboard'
    | '/em-delay'
    | '/funil'
    | '/hot'
    | '/onboarding'
    | '/planejamento'
    | '/pos-venda'
    | '/recomendacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/administracao'
    | '/apolices'
    | '/atividades'
    | '/calendario'
    | '/ciclo-revisao'
    | '/clientes'
    | '/dashboard'
    | '/em-delay'
    | '/funil'
    | '/hot'
    | '/onboarding'
    | '/planejamento'
    | '/pos-venda'
    | '/recomendacoes'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/administracao'
    | '/_authenticated/apolices'
    | '/_authenticated/atividades'
    | '/_authenticated/calendario'
    | '/_authenticated/ciclo-revisao'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/em-delay'
    | '/_authenticated/funil'
    | '/_authenticated/hot'
    | '/_authenticated/onboarding'
    | '/_authenticated/planejamento'
    | '/_authenticated/pos-venda'
    | '/_authenticated/recomendacoes'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recomendacoes': {
      id: '/_authenticated/recomendacoes'
      path: '/recomendacoes'
      fullPath: '/recomendacoes'
      preLoaderRoute: typeof AuthenticatedRecomendacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos-venda': {
      id: '/_authenticated/pos-venda'
      path: '/pos-venda'
      fullPath: '/pos-venda'
      preLoaderRoute: typeof AuthenticatedPosVendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento': {
      id: '/_authenticated/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AuthenticatedPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hot': {
      id: '/_authenticated/hot'
      path: '/hot'
      fullPath: '/hot'
      preLoaderRoute: typeof AuthenticatedHotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funil': {
      id: '/_authenticated/funil'
      path: '/funil'
      fullPath: '/funil'
      preLoaderRoute: typeof AuthenticatedFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/em-delay': {
      id: '/_authenticated/em-delay'
      path: '/em-delay'
      fullPath: '/em-delay'
      preLoaderRoute: typeof AuthenticatedEmDelayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ciclo-revisao': {
      id: '/_authenticated/ciclo-revisao'
      path: '/ciclo-revisao'
      fullPath: '/ciclo-revisao'
      preLoaderRoute: typeof AuthenticatedCicloRevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades': {
      id: '/_authenticated/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AuthenticatedAtividadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apolices': {
      id: '/_authenticated/apolices'
      path: '/apolices'
      fullPath: '/apolices'
      preLoaderRoute: typeof AuthenticatedApolicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedApolicesRoute: typeof AuthenticatedApolicesRoute
  AuthenticatedAtividadesRoute: typeof AuthenticatedAtividadesRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCicloRevisaoRoute: typeof AuthenticatedCicloRevisaoRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmDelayRoute: typeof AuthenticatedEmDelayRoute
  AuthenticatedFunilRoute: typeof AuthenticatedFunilRoute
  AuthenticatedHotRoute: typeof AuthenticatedHotRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanejamentoRoute: typeof AuthenticatedPlanejamentoRoute
  AuthenticatedPosVendaRoute: typeof AuthenticatedPosVendaRoute
  AuthenticatedRecomendacoesRoute: typeof AuthenticatedRecomendacoesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedApolicesRoute: AuthenticatedApolicesRoute,
  AuthenticatedAtividadesRoute: AuthenticatedAtividadesRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCicloRevisaoRoute: AuthenticatedCicloRevisaoRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmDelayRoute: AuthenticatedEmDelayRoute,
  AuthenticatedFunilRoute: AuthenticatedFunilRoute,
  AuthenticatedHotRoute: AuthenticatedHotRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanejamentoRoute: AuthenticatedPlanejamentoRoute,
  AuthenticatedPosVendaRoute: AuthenticatedPosVendaRoute,
  AuthenticatedRecomendacoesRoute: AuthenticatedRecomendacoesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
